dependencies:
  - name: jenkins
    version: 0.9.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: sonatype-nexus
    version: 0.1.1
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: pipelines
    version: 0.0.1
    repository: file://pipelines
  - name: exposecontroller
    version: 0.0.1
    repository: file://exposecontroller