dependencies:
  - name: jenkins
    version: 0.9.0
    repository: https://chartmuseum.helm.test.fabric8.io
  - name: sonatype-nexus
    version: 0.1.1
    repository: https://chartmuseum.helm.test.fabric8.io